/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Anderson
 */
public class PatientsEditForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientsForm
     */
    public PatientsEditForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LogoForm1 = new javax.swing.JLabel();
        MinisterioLogo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        NombreLabel1 = new javax.swing.JLabel();
        DUI1 = new javax.swing.JTextField();
        DuiLabel1 = new javax.swing.JLabel();
        Isss1 = new javax.swing.JTextField();
        IsssLabel1 = new javax.swing.JLabel();
        Age1 = new javax.swing.JTextField();
        AgeLabel1 = new javax.swing.JLabel();
        Birth1 = new javax.swing.JTextField();
        BirthLabel1 = new javax.swing.JLabel();
        VaxQLabel1 = new javax.swing.JLabel();
        LastName1 = new javax.swing.JTextField();
        LastNameLabel1 = new javax.swing.JLabel();
        VaxNameLabel1 = new javax.swing.JLabel();
        VaxDosisLabel1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JTextField();
        AddressLabel1 = new javax.swing.JLabel();
        CityLabel1 = new javax.swing.JLabel();
        StateLabel1 = new javax.swing.JLabel();
        Symptoms1 = new javax.swing.JTextField();
        SymptomsLabel1 = new javax.swing.JLabel();
        CurrentStateLabel1 = new javax.swing.JLabel();
        HospitalLabel2 = new javax.swing.JLabel();
        Kit1 = new javax.swing.JTextField();
        HospitalLabel3 = new javax.swing.JLabel();
        AdmitedLabel1 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Save1 = new javax.swing.JButton();
        personalInfoLabel1 = new javax.swing.JLabel();
        medicInfoLabel1 = new javax.swing.JLabel();
        genderLabel1 = new javax.swing.JLabel();
        VaxQ = new javax.swing.JComboBox<>();
        VaxName = new javax.swing.JComboBox<>();
        VaxDosis = new javax.swing.JComboBox<>();
        CurrentState = new javax.swing.JComboBox<>();
        Admited = new javax.swing.JComboBox<>();
        Hospital = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JComboBox<>();
        City = new javax.swing.JComboBox<>();
        State = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CovidApp - Formulario");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1010, 700));
        setSize(new java.awt.Dimension(1000, 475));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 1280));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 1280));

        LogoForm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        MinisterioLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Ministerio_De_Salud (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formulario para editar pacientes");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Nombre1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        NombreLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        NombreLabel1.setForeground(new java.awt.Color(204, 0, 0));
        NombreLabel1.setText("Nombres");

        DUI1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        DuiLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        DuiLabel1.setForeground(new java.awt.Color(204, 0, 0));
        DuiLabel1.setText("DUI");

        Isss1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        IsssLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        IsssLabel1.setForeground(new java.awt.Color(204, 0, 0));
        IsssLabel1.setText("Número de ISSS");

        Age1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AgeLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AgeLabel1.setForeground(new java.awt.Color(204, 0, 0));
        AgeLabel1.setText("Edad");

        Birth1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        BirthLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BirthLabel1.setForeground(new java.awt.Color(204, 0, 0));
        BirthLabel1.setText("Fecha de nacimiento");

        VaxQLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxQLabel1.setForeground(new java.awt.Color(204, 0, 0));
        VaxQLabel1.setText("¿Está vacunado?");

        LastName1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        LastNameLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        LastNameLabel1.setForeground(new java.awt.Color(204, 0, 0));
        LastNameLabel1.setText("Apellidos");

        VaxNameLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxNameLabel1.setForeground(new java.awt.Color(204, 0, 0));
        VaxNameLabel1.setText("¿Qué Vacuna?");

        VaxDosisLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxDosisLabel1.setForeground(new java.awt.Color(204, 0, 0));
        VaxDosisLabel1.setText("¿Cuántas dosis?");

        Address1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AddressLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AddressLabel1.setForeground(new java.awt.Color(204, 0, 0));
        AddressLabel1.setText("Dirección");

        CityLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CityLabel1.setForeground(new java.awt.Color(204, 0, 0));
        CityLabel1.setText("Municipio");

        StateLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        StateLabel1.setForeground(new java.awt.Color(204, 0, 0));
        StateLabel1.setText("Departamento");

        Symptoms1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        SymptomsLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        SymptomsLabel1.setForeground(new java.awt.Color(204, 0, 0));
        SymptomsLabel1.setText("Síntomas");

        CurrentStateLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CurrentStateLabel1.setForeground(new java.awt.Color(204, 0, 0));
        CurrentStateLabel1.setText("Estado");

        HospitalLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel2.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel2.setText("Hospital");

        Kit1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        HospitalLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel3.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel3.setText("Kits entregados");

        AdmitedLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AdmitedLabel1.setForeground(new java.awt.Color(204, 0, 0));
        AdmitedLabel1.setText("Ingresado");

        Save.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(204, 0, 0));
        Save.setText("Guardar Edición");
        Save.setFocusable(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Save1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save1.setForeground(new java.awt.Color(204, 0, 0));
        Save1.setText("Regresar al Menú");
        Save1.setFocusable(false);

        personalInfoLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        personalInfoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInfoLabel1.setText("Datos Personales");
        personalInfoLabel1.setAlignmentX(0.5F);
        personalInfoLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        medicInfoLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        medicInfoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medicInfoLabel1.setText("Datos Medicos");
        medicInfoLabel1.setAlignmentX(0.5F);
        medicInfoLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        genderLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        genderLabel1.setForeground(new java.awt.Color(204, 0, 0));
        genderLabel1.setText("Genero");

        VaxQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VaxName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VaxDosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CurrentState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Admited.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Hospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        State.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(personalInfoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(834, 834, 834))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Age1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nombre1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Birth1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(LastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MinisterioLogo1)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addGap(445, 445, 445))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(BirthLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(AgeLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(NombreLabel1)
                                .addGap(104, 104, 104)
                                .addComponent(LastNameLabel1)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(genderLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(DuiLabel1)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(medicInfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(CurrentStateLabel1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Kit1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                    .addComponent(VaxQ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CurrentState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(AdmitedLabel1)
                                                .addGap(96, 96, 96)
                                                .addComponent(HospitalLabel2))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(LogoForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(Symptoms1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(VaxName, 0, 145, Short.MAX_VALUE)
                                                                    .addComponent(Admited, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(VaxDosis, 0, 149, Short.MAX_VALUE)
                                                                    .addComponent(Hospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VaxQLabel1)
                                .addGap(67, 67, 67)
                                .addComponent(VaxNameLabel1)
                                .addGap(70, 70, 70)
                                .addComponent(VaxDosisLabel1)
                                .addGap(102, 102, 102))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(AddressLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Isss1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(CityLabel1)
                                .addGap(82, 82, 82)
                                .addComponent(StateLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(IsssLabel1)))
                        .addGap(264, 264, 264)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Save)
                                .addGap(39, 39, 39)
                                .addComponent(Save1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(HospitalLabel3)
                                .addGap(163, 163, 163)
                                .addComponent(SymptomsLabel1)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinisterioLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(personalInfoLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreLabel1)
                                .addComponent(DuiLabel1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(medicInfoLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VaxQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VaxDosisLabel1)
                            .addComponent(VaxNameLabel1)
                            .addComponent(VaxQLabel1))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Age1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Birth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AgeLabel1)
                                    .addComponent(BirthLabel1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CurrentStateLabel1)
                                    .addComponent(AdmitedLabel1)
                                    .addComponent(HospitalLabel2)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CurrentState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(genderLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Kit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Symptoms1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CityLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StateLabel1)
                        .addComponent(HospitalLabel3)
                        .addComponent(SymptomsLabel1)))
                .addGap(46, 46, 46)
                .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel1)
                .addGap(18, 18, 18)
                .addComponent(Isss1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Save)
                        .addComponent(Save1))
                    .addComponent(IsssLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsEditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address1;
    private javax.swing.JLabel AddressLabel1;
    private javax.swing.JComboBox<String> Admited;
    private javax.swing.JLabel AdmitedLabel1;
    private javax.swing.JTextField Age1;
    private javax.swing.JLabel AgeLabel1;
    private javax.swing.JTextField Birth1;
    private javax.swing.JLabel BirthLabel1;
    private javax.swing.JComboBox<String> City;
    private javax.swing.JLabel CityLabel1;
    private javax.swing.JComboBox<String> CurrentState;
    private javax.swing.JLabel CurrentStateLabel1;
    private javax.swing.JTextField DUI1;
    private javax.swing.JLabel DuiLabel1;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JComboBox<String> Hospital;
    private javax.swing.JLabel HospitalLabel2;
    private javax.swing.JLabel HospitalLabel3;
    private javax.swing.JTextField Isss1;
    private javax.swing.JLabel IsssLabel1;
    private javax.swing.JTextField Kit1;
    private javax.swing.JTextField LastName1;
    private javax.swing.JLabel LastNameLabel1;
    private javax.swing.JLabel LogoForm1;
    private javax.swing.JLabel MinisterioLogo1;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JLabel NombreLabel1;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private javax.swing.JComboBox<String> State;
    private javax.swing.JLabel StateLabel1;
    private javax.swing.JTextField Symptoms1;
    private javax.swing.JLabel SymptomsLabel1;
    private javax.swing.JComboBox<String> VaxDosis;
    private javax.swing.JLabel VaxDosisLabel1;
    private javax.swing.JComboBox<String> VaxName;
    private javax.swing.JLabel VaxNameLabel1;
    private javax.swing.JComboBox<String> VaxQ;
    private javax.swing.JLabel VaxQLabel1;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel medicInfoLabel1;
    private javax.swing.JLabel personalInfoLabel1;
    // End of variables declaration//GEN-END:variables
}
