/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Anderson
 */
public class PatientsInsertForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientsForm
     */
    public PatientsInsertForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoForm = new javax.swing.JLabel();
        MinisterioLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        DUI = new javax.swing.JTextField();
        DuiLabel = new javax.swing.JLabel();
        Isss = new javax.swing.JTextField();
        IsssLabel = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        Birth = new javax.swing.JTextField();
        BirthLabel = new javax.swing.JLabel();
        VaxQLabel = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        VaxNameLabel = new javax.swing.JLabel();
        VaxDosisLabel = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        Symptoms = new javax.swing.JTextField();
        SymptomsLabel = new javax.swing.JLabel();
        CurrentStateLabel = new javax.swing.JLabel();
        HospitalLabel = new javax.swing.JLabel();
        Kit = new javax.swing.JTextField();
        HospitalLabel1 = new javax.swing.JLabel();
        AdmitedLabel = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Save1 = new javax.swing.JButton();
        personalInfoLabel = new javax.swing.JLabel();
        medicInfoLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        VaxQ = new javax.swing.JComboBox<>();
        VaxName = new javax.swing.JComboBox<>();
        VaxDosis = new javax.swing.JComboBox<>();
        CurrentState = new javax.swing.JComboBox<>();
        Admited = new javax.swing.JComboBox<>();
        Hospital = new javax.swing.JComboBox<>();
        City = new javax.swing.JComboBox<>();
        State = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CovidApp - Formulario");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1010, 700));
        setMinimumSize(new java.awt.Dimension(1010, 700));
        setPreferredSize(new java.awt.Dimension(900, 475));
        setSize(new java.awt.Dimension(1000, 475));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1280));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1280));

        LogoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        MinisterioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Ministerio_De_Salud (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario para añadir nuevo paciente");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Nombre.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        NombreLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(204, 0, 0));
        NombreLabel.setText("Nombres");

        DUI.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        DuiLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        DuiLabel.setForeground(new java.awt.Color(204, 0, 0));
        DuiLabel.setText("DUI");

        Isss.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        IsssLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        IsssLabel.setForeground(new java.awt.Color(204, 0, 0));
        IsssLabel.setText("Número de ISSS");

        Age.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AgeLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(204, 0, 0));
        AgeLabel.setText("Edad");

        Birth.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        BirthLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BirthLabel.setForeground(new java.awt.Color(204, 0, 0));
        BirthLabel.setText("Fecha de nacimiento");

        VaxQLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxQLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxQLabel.setText("¿Está vacunado?");

        LastName.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        LastNameLabel.setText("Apellidos");

        VaxNameLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxNameLabel.setText("¿Qué Vacuna?");

        VaxDosisLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxDosisLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxDosisLabel.setText("¿Cuántas dosis?");

        Address.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AddressLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(204, 0, 0));
        AddressLabel.setText("Dirección");

        CityLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(204, 0, 0));
        CityLabel.setText("Municipio");

        StateLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(204, 0, 0));
        StateLabel.setText("Departamento");

        Symptoms.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        SymptomsLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        SymptomsLabel.setForeground(new java.awt.Color(204, 0, 0));
        SymptomsLabel.setText("Síntomas");

        CurrentStateLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CurrentStateLabel.setForeground(new java.awt.Color(204, 0, 0));
        CurrentStateLabel.setText("Estado");

        HospitalLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel.setText("Hospital");

        Kit.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        HospitalLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel1.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel1.setText("Kits entregados");

        AdmitedLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AdmitedLabel.setForeground(new java.awt.Color(204, 0, 0));
        AdmitedLabel.setText("Ingresado");

        Save.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(204, 0, 0));
        Save.setText("Guardar Paciente");
        Save.setFocusable(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Save1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save1.setForeground(new java.awt.Color(204, 0, 0));
        Save1.setText("Regresar al Menú");
        Save1.setFocusable(false);

        personalInfoLabel.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        personalInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInfoLabel.setText("Datos Personales");
        personalInfoLabel.setAlignmentX(0.5F);
        personalInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        medicInfoLabel.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        medicInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medicInfoLabel.setText("Datos Medicos");
        medicInfoLabel.setAlignmentX(0.5F);
        medicInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        genderLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(204, 0, 0));
        genderLabel.setText("Genero");

        VaxQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VaxName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VaxDosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CurrentState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Admited.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Hospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        State.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MinisterioLogo)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(445, 445, 445))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(AgeLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(NombreLabel)
                                        .addGap(104, 104, 104)
                                        .addComponent(LastNameLabel)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(genderLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(DuiLabel)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(84, 84, 84)
                                                        .addComponent(Save)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(Save1))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(50, 50, 50)
                                                        .addComponent(medicInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(155, 155, 155)
                                                        .addComponent(CurrentStateLabel))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(135, 135, 135)
                                                        .addComponent(HospitalLabel1))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(106, 106, 106)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(Kit, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                            .addComponent(VaxQ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(CurrentState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(56, 56, 56)
                                                        .addComponent(AdmitedLabel)
                                                        .addGap(96, 96, 96)
                                                        .addComponent(HospitalLabel))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(137, 137, 137)
                                                        .addComponent(SymptomsLabel))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(LogoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(VaxDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(4, 4, 4))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(Symptoms)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(VaxQLabel)
                                        .addGap(65, 65, 65)
                                        .addComponent(VaxNameLabel)
                                        .addGap(76, 76, 76)
                                        .addComponent(VaxDosisLabel)
                                        .addGap(156, 156, 156))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(personalInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(834, 834, 834))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(CityLabel)
                                                .addGap(90, 90, 90)
                                                .addComponent(StateLabel))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Age, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(BirthLabel))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(DUI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(Address)
                                    .addComponent(Isss, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(AddressLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(IsssLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinisterioLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(personalInfoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreLabel)
                                .addComponent(DuiLabel))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(medicInfoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VaxQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VaxDosisLabel)
                            .addComponent(VaxNameLabel)
                            .addComponent(VaxQLabel))))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AgeLabel)
                                .addComponent(BirthLabel)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentStateLabel)
                            .addComponent(AdmitedLabel)
                            .addComponent(HospitalLabel))))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Symptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalLabel1)
                            .addComponent(SymptomsLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityLabel)
                            .addComponent(StateLabel))))
                .addGap(11, 11, 11)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save)
                    .addComponent(Save1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IsssLabel)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsInsertForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JComboBox<String> Admited;
    private javax.swing.JLabel AdmitedLabel;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField Birth;
    private javax.swing.JLabel BirthLabel;
    private javax.swing.JComboBox<String> City;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JComboBox<String> CurrentState;
    private javax.swing.JLabel CurrentStateLabel;
    private javax.swing.JTextField DUI;
    private javax.swing.JLabel DuiLabel;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JComboBox<String> Hospital;
    private javax.swing.JLabel HospitalLabel;
    private javax.swing.JLabel HospitalLabel1;
    private javax.swing.JTextField Isss;
    private javax.swing.JLabel IsssLabel;
    private javax.swing.JTextField Kit;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LogoForm;
    private javax.swing.JLabel MinisterioLogo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private javax.swing.JComboBox<String> State;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JTextField Symptoms;
    private javax.swing.JLabel SymptomsLabel;
    private javax.swing.JComboBox<String> VaxDosis;
    private javax.swing.JLabel VaxDosisLabel;
    private javax.swing.JComboBox<String> VaxName;
    private javax.swing.JLabel VaxNameLabel;
    private javax.swing.JComboBox<String> VaxQ;
    private javax.swing.JLabel VaxQLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel medicInfoLabel;
    private javax.swing.JLabel personalInfoLabel;
    // End of variables declaration//GEN-END:variables
}
