/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Anderson
 */
public class PatientsDeletetForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientsForm
     */
    public PatientsDeletetForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoForm = new javax.swing.JLabel();
        MinisterioLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        DUI = new javax.swing.JTextField();
        DuiLabel = new javax.swing.JLabel();
        Isss = new javax.swing.JTextField();
        IsssLabel = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        Birth = new javax.swing.JTextField();
        BirthLabel = new javax.swing.JLabel();
        VaxQLabel = new javax.swing.JLabel();
        VaxQ = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        VaxName = new javax.swing.JTextField();
        VaxNameLabel = new javax.swing.JLabel();
        VaxDosis = new javax.swing.JTextField();
        VaxDosisLabel = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        StateLabel = new javax.swing.JLabel();
        Symptoms = new javax.swing.JTextField();
        SymptomsLabel = new javax.swing.JLabel();
        CurrentState = new javax.swing.JTextField();
        CurrentStateLabel = new javax.swing.JLabel();
        Hospital = new javax.swing.JTextField();
        HospitalLabel = new javax.swing.JLabel();
        Kit = new javax.swing.JTextField();
        HospitalLabel1 = new javax.swing.JLabel();
        AdmitedLabel = new javax.swing.JLabel();
        Admited = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        personalInfoLabel = new javax.swing.JLabel();
        medicInfoLabel = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CovidApp - Formulario");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1010, 700));
        setSize(new java.awt.Dimension(1000, 475));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1280));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1280));

        LogoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        MinisterioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Ministerio_De_Salud (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario para eliminar paciente");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Nombre.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        NombreLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(204, 0, 0));
        NombreLabel.setText("Nombres");

        DUI.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        DuiLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        DuiLabel.setForeground(new java.awt.Color(204, 0, 0));
        DuiLabel.setText("DUI");

        Isss.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        IsssLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        IsssLabel.setForeground(new java.awt.Color(204, 0, 0));
        IsssLabel.setText("Número de ISSS");

        Age.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AgeLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(204, 0, 0));
        AgeLabel.setText("Edad");

        Birth.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        BirthLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BirthLabel.setForeground(new java.awt.Color(204, 0, 0));
        BirthLabel.setText("Fecha de nacimiento");

        VaxQLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxQLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxQLabel.setText("¿Está vacunado?");

        VaxQ.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        LastName.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        LastNameLabel.setText("Apellidos");

        VaxName.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        VaxNameLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxNameLabel.setText("¿Qué Vacuna?");

        VaxDosis.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        VaxDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaxDosisActionPerformed(evt);
            }
        });

        VaxDosisLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxDosisLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxDosisLabel.setText("¿Cuántas dosis?");

        Address.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AddressLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(204, 0, 0));
        AddressLabel.setText("Dirección");

        City.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        CityLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(204, 0, 0));
        CityLabel.setText("Municipio");

        State.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        StateLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(204, 0, 0));
        StateLabel.setText("Departamento");

        Symptoms.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        SymptomsLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        SymptomsLabel.setForeground(new java.awt.Color(204, 0, 0));
        SymptomsLabel.setText("Síntomas");

        CurrentState.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        CurrentStateLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CurrentStateLabel.setForeground(new java.awt.Color(204, 0, 0));
        CurrentStateLabel.setText("Estado");

        Hospital.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        HospitalLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel.setText("Hospital");

        Kit.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        HospitalLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel1.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel1.setText("Kits entregados");

        AdmitedLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AdmitedLabel.setForeground(new java.awt.Color(204, 0, 0));
        AdmitedLabel.setText("Ingresado");

        Admited.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        DeleteButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(204, 0, 0));
        DeleteButton.setText("Eliminar Paciente");
        DeleteButton.setFocusable(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(204, 0, 0));
        CancelButton.setText("Cancelar");
        CancelButton.setFocusable(false);

        personalInfoLabel.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        personalInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInfoLabel.setText("Datos Personales");
        personalInfoLabel.setAlignmentX(0.5F);
        personalInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        medicInfoLabel.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        medicInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medicInfoLabel.setText("Datos Medicos");
        medicInfoLabel.setAlignmentX(0.5F);
        medicInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        gender.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(204, 0, 0));
        genderLabel.setText("Genero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(personalInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(834, 834, 834))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(CityLabel)
                                                .addGap(90, 90, 90)
                                                .addComponent(StateLabel))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Age, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DUI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Address)
                                    .addComponent(Isss))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MinisterioLogo)
                        .addGap(445, 840, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(BirthLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(AgeLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(NombreLabel)
                                .addGap(104, 104, 104)
                                .addComponent(LastNameLabel)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(genderLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(DuiLabel)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(VaxQLabel)
                                .addGap(69, 69, 69)
                                .addComponent(VaxNameLabel)
                                .addGap(75, 75, 75)
                                .addComponent(VaxDosisLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(medicInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CurrentState, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(CurrentStateLabel))
                                            .addComponent(Kit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(HospitalLabel1)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Symptoms, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(49, 49, 49)
                                                        .addComponent(AdmitedLabel)
                                                        .addGap(110, 110, 110)
                                                        .addComponent(HospitalLabel))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(137, 137, 137)
                                                        .addComponent(SymptomsLabel)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(VaxQ, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(VaxDosis, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(Hospital)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(DeleteButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(127, 127, 127)
                                .addComponent(LogoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(AddressLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(IsssLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinisterioLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(personalInfoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreLabel)
                                .addComponent(DuiLabel))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(medicInfoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VaxQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VaxDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VaxQLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VaxDosisLabel)
                                .addComponent(VaxNameLabel)))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeLabel)
                            .addComponent(BirthLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CurrentState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentStateLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdmitedLabel)
                            .addComponent(HospitalLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Symptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HospitalLabel1)
                            .addComponent(SymptomsLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityLabel)
                            .addComponent(StateLabel))))
                .addGap(11, 11, 11)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton)
                    .addComponent(CancelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IsssLabel)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void VaxDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaxDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VaxDosisActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsDeletetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsDeletetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsDeletetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsDeletetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsDeletetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField Admited;
    private javax.swing.JLabel AdmitedLabel;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField Birth;
    private javax.swing.JLabel BirthLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField City;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CurrentState;
    private javax.swing.JLabel CurrentStateLabel;
    private javax.swing.JTextField DUI;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DuiLabel;
    private javax.swing.JTextField Hospital;
    private javax.swing.JLabel HospitalLabel;
    private javax.swing.JLabel HospitalLabel1;
    private javax.swing.JTextField Isss;
    private javax.swing.JLabel IsssLabel;
    private javax.swing.JTextField Kit;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LogoForm;
    private javax.swing.JLabel MinisterioLogo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField State;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JTextField Symptoms;
    private javax.swing.JLabel SymptomsLabel;
    private javax.swing.JTextField VaxDosis;
    private javax.swing.JLabel VaxDosisLabel;
    private javax.swing.JTextField VaxName;
    private javax.swing.JLabel VaxNameLabel;
    private javax.swing.JTextField VaxQ;
    private javax.swing.JLabel VaxQLabel;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel medicInfoLabel;
    private javax.swing.JLabel personalInfoLabel;
    // End of variables declaration//GEN-END:variables
}
