/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author Anderson
 */
public class PatientsForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientsForm
     */
    public PatientsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoForm = new javax.swing.JLabel();
        MinisterioLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        DUI = new javax.swing.JTextField();
        DuiLabel = new javax.swing.JLabel();
        Isss = new javax.swing.JTextField();
        IsssLabel = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        Birth = new javax.swing.JTextField();
        BirthLabel = new javax.swing.JLabel();
        VaxQLabel = new javax.swing.JLabel();
        VaxQ = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        VaxName = new javax.swing.JTextField();
        VaxNameLabel = new javax.swing.JLabel();
        VaxDosis = new javax.swing.JTextField();
        VaxDosisLabel = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        StateLabel = new javax.swing.JLabel();
        Symptoms = new javax.swing.JTextField();
        SymptomsLabel = new javax.swing.JLabel();
        CurrentState = new javax.swing.JTextField();
        CurrentStateLabel = new javax.swing.JLabel();
        Hospital = new javax.swing.JTextField();
        HospitalLabel = new javax.swing.JLabel();
        Kit = new javax.swing.JTextField();
        HospitalLabel1 = new javax.swing.JLabel();
        AdmitedLabel = new javax.swing.JLabel();
        Admited = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Save1 = new javax.swing.JButton();
        Save2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CovidApp - Formulario");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        LogoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        LogoForm.setMaximumSize(new java.awt.Dimension(200, 200));
        LogoForm.setMinimumSize(new java.awt.Dimension(200, 200));
        LogoForm.setPreferredSize(new java.awt.Dimension(200, 200));

        MinisterioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Ministerio_De_Salud (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario para añadir nuevo paciente");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Nombre.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        NombreLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(204, 0, 0));
        NombreLabel.setText("Nombres");

        DUI.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        DuiLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        DuiLabel.setForeground(new java.awt.Color(204, 0, 0));
        DuiLabel.setText("Número de DUI");

        Isss.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        IsssLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        IsssLabel.setForeground(new java.awt.Color(204, 0, 0));
        IsssLabel.setText("Número de ISSS");

        Age.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AgeLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(204, 0, 0));
        AgeLabel.setText("Edad");

        Birth.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        BirthLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BirthLabel.setForeground(new java.awt.Color(204, 0, 0));
        BirthLabel.setText("Fecha de nacimiento");

        VaxQLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxQLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxQLabel.setText("¿Está vacunado?");

        VaxQ.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        LastName.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        LastNameLabel.setText("Apellidos");

        VaxName.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        VaxNameLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxNameLabel.setText("¿Qué Vacuna?");

        VaxDosis.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        VaxDosisLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        VaxDosisLabel.setForeground(new java.awt.Color(204, 0, 0));
        VaxDosisLabel.setText("¿Cuántas dosis?");

        Address.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        AddressLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(204, 0, 0));
        AddressLabel.setText("Dirección");

        City.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        CityLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(204, 0, 0));
        CityLabel.setText("Municipio");

        State.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        StateLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(204, 0, 0));
        StateLabel.setText("Departamento");

        Symptoms.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        SymptomsLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        SymptomsLabel.setForeground(new java.awt.Color(204, 0, 0));
        SymptomsLabel.setText("Síntomas");

        CurrentState.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        CurrentStateLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CurrentStateLabel.setForeground(new java.awt.Color(204, 0, 0));
        CurrentStateLabel.setText("Estado");

        Hospital.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        HospitalLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel.setText("Hospital");

        Kit.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        HospitalLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        HospitalLabel1.setForeground(new java.awt.Color(204, 0, 0));
        HospitalLabel1.setText("Kits entrgados");

        AdmitedLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        AdmitedLabel.setForeground(new java.awt.Color(204, 0, 0));
        AdmitedLabel.setText("Ingresado");

        Admited.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N

        Save.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(204, 0, 0));
        Save.setText("Guardar Paciente");

        Save1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save1.setForeground(new java.awt.Color(204, 0, 0));
        Save1.setText("Regresar al Menú");

        Save2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        Save2.setForeground(new java.awt.Color(204, 0, 0));
        Save2.setText("Agregar uno nuevo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(NombreLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(LastNameLabel))))
                            .addComponent(MinisterioLogo))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DUI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(DuiLabel)
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(IsssLabel)
                                        .addGap(221, 221, 221))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Isss, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(AgeLabel)
                                        .addGap(25, 25, 25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(BirthLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VaxQ, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(VaxQLabel))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(58, 58, 58)
                                .addComponent(LogoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CurrentState, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(CurrentStateLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(AdmitedLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(HospitalLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(HospitalLabel1)
                                        .addGap(183, 183, 183)
                                        .addComponent(Save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Save2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Save1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(VaxNameLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VaxDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(VaxDosisLabel)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(AddressLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(CityLabel)
                                        .addGap(44, 44, 44)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(StateLabel))
                                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(SymptomsLabel))
                                    .addComponent(Symptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(111, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinisterioLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Isss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IsssLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastNameLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DuiLabel)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AgeLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(VaxQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VaxQLabel)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VaxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VaxNameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VaxDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VaxDosisLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Symptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SymptomsLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CityLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StateLabel)))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CurrentState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentStateLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HospitalLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Kit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Save)
                                .addComponent(Save1)
                                .addComponent(Save2))
                            .addComponent(HospitalLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdmitedLabel)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField Admited;
    private javax.swing.JLabel AdmitedLabel;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField Birth;
    private javax.swing.JLabel BirthLabel;
    private javax.swing.JTextField City;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CurrentState;
    private javax.swing.JLabel CurrentStateLabel;
    private javax.swing.JTextField DUI;
    private javax.swing.JLabel DuiLabel;
    private javax.swing.JTextField Hospital;
    private javax.swing.JLabel HospitalLabel;
    private javax.swing.JLabel HospitalLabel1;
    private javax.swing.JTextField Isss;
    private javax.swing.JLabel IsssLabel;
    private javax.swing.JTextField Kit;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LogoForm;
    private javax.swing.JLabel MinisterioLogo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private javax.swing.JButton Save2;
    private javax.swing.JTextField State;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JTextField Symptoms;
    private javax.swing.JLabel SymptomsLabel;
    private javax.swing.JTextField VaxDosis;
    private javax.swing.JLabel VaxDosisLabel;
    private javax.swing.JTextField VaxName;
    private javax.swing.JLabel VaxNameLabel;
    private javax.swing.JTextField VaxQ;
    private javax.swing.JLabel VaxQLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
